# Generated by Django 4.0.2 on 2022-02-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=50)),
                ('player1_score', models.IntegerField(default=0)),
                ('player2', models.CharField(max_length=50)),
                ('player2_score', models.IntegerField(default=0)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('player1_team', models.CharField(max_length=50)),
                ('player2_team', models.CharField(max_length=50)),
            ],
        ),
    ]
