# Generated by Django 3.2.12 on 2022-12-09 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('player_id', models.IntegerField()),
                ('player_name', models.CharField(max_length=50)),
                ('player_team', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid1', models.IntegerField()),
                ('userid2', models.IntegerField()),
                ('player1', models.CharField(max_length=100)),
                ('player2', models.CharField(max_length=100)),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('choose_player', models.IntegerField(blank=True, default=1, null=True)),
                ('inningHalf', models.IntegerField(default=0)),
                ('teamSwitching', models.BooleanField(default=True)),
                ('positions1', models.BooleanField()),
                ('position2', models.BooleanField()),
                ('position3', models.BooleanField(default=0)),
                ('topBottom', models.IntegerField(null=True)),
                ('inning', models.IntegerField()),
                ('balls', models.IntegerField()),
                ('outs', models.IntegerField()),
                ('donehits', models.IntegerField()),
                ('EH', models.BooleanField()),
                ('hitCount', models.IntegerField(default=9)),
                ('activeGameStep', models.IntegerField(default=0)),
                ('gameState', models.JSONField(blank=True, default=[])),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=50)),
                ('player1_score', models.IntegerField(default=0)),
                ('player2', models.CharField(max_length=50)),
                ('player2_score', models.IntegerField(default=0)),
                ('dateTime', models.DateTimeField()),
                ('player1_team', models.CharField(max_length=50)),
                ('player2_team', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
