# Generated by Django 3.2.12 on 2022-08-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20220405_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumegame',
            name='choose_player',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
