# Generated by Django 4.0.2 on 2022-02-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_remove_usertable_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='user_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
