# Generated by Django 4.0.2 on 2022-02-10 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0005_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='user',
            new_name='email',
        ),
    ]
